var fs = require('fs');

// Expand express app and helpful functions from parent.
var self = require('../app')
  , app = self.app
  , getSessionUser = self.getSessionUser;


/**
 * Routes
 */

function getPrinters () {
  // Read from ../data/printers.txt, generated by ../tools/update_printers.sh
  return fs.readFileSync(__dirname + '/../data/printers.txt', 'utf-8').split(/\s+/).filter(function (printer) {
    // No empty strings
    return !!printer;
  }).map(function (printer) {
    return {
      id: printer,
      url: 'http://' + printer + '.olin.edu/',
      building: ((printer.match(/^[a-z]+/i) || [])[0] || '').toUpperCase(),
      room: (printer.match(/\d+[^hx]*/) || [])[0],
      type: printer.match(/h\d+$/) ? 'Hewlett-Packard'
        : printer.match(/x\d+$/) ? 'Xerox'
        : 'Unknown',
      number: (printer.match(/\d+$/) || [])[0]
    }
  });
}

app.get('/printers', function (req, res) {
  getSessionUser(req, function (err, user) {
    console.log(err, user);
    res.render('printers.jade', {
      title: 'Olin Apps',
      printers: getPrinters(),
      user: user
    });
  })
})